name: "Orchestrator Workflow"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Action to execute (promote-uat or promote-prod)"
        required: true
        type: string
      stable_tag:
        description: "Stable Docker tag to be promoted"
        required: false
        type: string
        default: "stable"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Build PR Docker Image
        id: pr_image
        if: ${{ github.event_name == 'pull_request' }}
        uses: pagopa/eng-github-actions-iac-template/global/ci-cd-paflow/build-pr@PAYMCLOUD-480-new-workflow-deploy
        with:
          github_token: ${{ github.token }}
          docker_context_path: "./test-docker"
          docker_registry: "ghcr.io"
          pr_number: ${{ github.event.number }}

  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stable Docker Image for Main
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: pagopa/eng-github-actions-iac-template/global/ci-cd-paflow/build-main@PAYMCLOUD-480-new-workflow-deploy
        with:
          github_token: ${{ github.token }}
          docker_context_path: "./test-docker"

  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Promote Docker Image to the Environment
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: pagopa/eng-github-actions-iac-template/global/ci-cd-paflow/promote@PAYMCLOUD-480-new-workflow-deploy
        with:
          github_token: ${{ github.token }}
          environment: ${{ github.event.inputs.action == 'promote-uat' && 'uat' || 'prod' }}
          stable_tag: ${{ github.event.inputs.stable_tag }}