name: Call OctoPus Workflow

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Specify promotion target (promote-uat or promote-prod)"
        required: true
        type: choice
        options:
          - promote-uat
          - promote-prod
      stable_tag:
        description: "The stable Docker tag to promote"
        required: false
        default: "stabilisssssimo"

permissions:
  contents: read
  id-token: write

jobs:
  orchestrator:
    name: Invoke Orchestrator Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Call Reusable Orchestrator Workflow
        uses: ./.github/workflows/ci-cd-paflow/orchestrator.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          action: ${{ inputs.action }}
          stable_tag: ${{ inputs.stable_tag }}
